"""Fabric capacity sizing from workload assumptions. ESTIMATES ONLY.

Fabric bills a capacity (F2 ... F2048, the number is capacity units, CU) by the hour, and every
workload draws CU-seconds from it. Background jobs are smoothed over 24 hours; interactive work is
smoothed over minutes, so the busy five minutes decide the size. The sizing rule here:

    required CU = background CU-seconds per day / 86,400
                + interactive CU-seconds per day / business-hours seconds x peak factor

then pick the smallest SKU where required CU <= target utilisation x SKU. Costs use the
illustrative price in finops/workloads.yaml. Nothing here was measured on a real capacity; the
point is a defensible starting size and a clear list of what to measure in a pilot."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from fabricbi.paths import FINOPS_DIR


@dataclass
class Sizing:
    background_cu: float
    interactive_peak_cu: float
    required_cu: float
    sku: int
    utilisation: float
    monthly_payg_usd: float
    monthly_reserved_usd: float
    monthly_dev_paused_usd: float
    foundry_monthly_usd: float
    per_workload: dict[str, dict]


def load(path: Path = FINOPS_DIR / "workloads.yaml") -> dict:
    return yaml.safe_load(path.read_text())


def size(spec: dict | None = None, scale: float = 1.0) -> Sizing:
    spec = spec or load()
    a = spec["assumptions"]
    biz_seconds = a["business_hours_per_day"] * 3600
    per, bg, inter = {}, 0.0, 0.0
    for name, w in spec["workloads"].items():
        daily = w["cu_seconds_per_run"] * w["runs_per_day"] * scale
        if w["kind"] == "background":
            cu = daily / 86400
            bg += cu
        else:
            cu = daily / biz_seconds * a["interactive_peak_factor"]
            inter += cu
        per[name] = {
            "kind": w["kind"],
            "cu_seconds_per_day": round(daily),
            "cu": round(cu, 3),
            "note": w["note"],
        }
    required = bg + inter
    sku = next((s for s in spec["skus"] if required <= a["target_utilisation"] * s), spec["skus"][-1])
    price = a["price_per_cu_hour_usd"]
    f = spec["foundry"]
    foundry = (
        f["questions_per_day"] * scale * f["tokens_per_question"] * 30 / 1e6 * f["usd_per_million_tokens"]
    )
    return Sizing(
        background_cu=round(bg, 3),
        interactive_peak_cu=round(inter, 3),
        required_cu=round(required, 3),
        sku=sku,
        utilisation=round(required / sku, 3),
        monthly_payg_usd=round(sku * price * a["hours_per_month"], 2),
        monthly_reserved_usd=round(sku * price * a["hours_per_month"] * (1 - a["reserved_discount"]), 2),
        monthly_dev_paused_usd=round(spec["skus"][0] * price * a["dev_hours_per_month"], 2),
        foundry_monthly_usd=round(foundry, 2),
        per_workload=per,
    )


def markdown(s: Sizing, scales: tuple[float, ...] = (1.0, 5.0, 25.0)) -> str:
    lines = [
        "# Cost estimate (Fabric capacity and surrounding Azure services)",
        "",
        "> **Estimates only.** Generated by `python scripts/cost_report.py` from the assumptions in",
        "> [`finops/workloads.yaml`](../finops/workloads.yaml). Nothing has run on a real capacity, and the",
        "> prices are illustrative list prices that vary by region and change over time. Check the",
        "> [Fabric pricing page](https://azure.microsoft.com/pricing/details/microsoft-fabric/) and replace",
        "> the workload numbers with readings from the Fabric Capacity Metrics app after a pilot.",
        "",
        "## Capacity sizing at the assumed load",
        "",
        "| Workload | Kind | CU-seconds / day | CU drawn | Note |",
        "|---|---|---:|---:|---|",
    ]
    for n, w in s.per_workload.items():
        lines.append(f"| {n} | {w['kind']} | {w['cu_seconds_per_day']:,} | {w['cu']} | {w['note']} |")
    lines += [
        "",
        f"Background {s.background_cu} CU + interactive peak {s.interactive_peak_cu} CU = **{s.required_cu} CU required**, "
        f"so the smallest SKU with 20% headroom is **F{s.sku}** ({s.utilisation:.0%} utilised).",
        "",
        "## Monthly cost by scale (estimates)",
        "",
        "| Load vs assumed | Required CU | SKU | Pay-as-you-go | One-year reserved | Foundry tokens (data agent) |",
        "|---|---:|---|---:|---:|---:|",
    ]
    for sc in scales:
        x = size(scale=sc)
        lines.append(
            f"| {sc:g}x | {x.required_cu} | F{x.sku} | ${x.monthly_payg_usd:,.0f} | ${x.monthly_reserved_usd:,.0f} | ${x.foundry_monthly_usd:,.2f} |"
        )
    lines += [
        "",
        f"A dev F{load()['skus'][0]} capacity paused outside working hours ({load()['assumptions']['dev_hours_per_month']} hours a month) "
        f"comes to about **${s.monthly_dev_paused_usd:,.0f} a month**. A Fabric trial capacity costs nothing and is enough for a first walkthrough.",
        "",
        "## Surrounding Azure services (dev, smallest SKUs)",
        "",
        "| Service | Dev setting in IaC | Rough monthly cost |",
        "|---|---|---|",
        "| Event Hubs | Basic, 1 throughput unit | about $11 |",
        "| IoT Hub | F1 free tier (one per subscription; use B1 if taken) | $0 (B1 about $10) |",
        "| Storage (ADLS Gen2 landing zone) | Standard LRS, a few GB | under $1 |",
        "| Key Vault | Standard, RBAC | under $1 |",
        "| Log Analytics + App Insights | 1 GB/day cap, 30-day retention | a few dollars at test volumes |",
        "| Microsoft Purview | off in dev (`deploy_purview = false`), on in prod | check current Purview pricing before enabling |",
        "",
        "## How to keep dev cheap",
        "",
        "- Pause the Fabric capacity when not in use (`az fabric capacity suspend`); a paused capacity is not billed for compute.",
        "- Run `teardown.yml` after a test; every resource is in one resource group per environment.",
        "- Keep the Log Analytics daily cap; set an Azure budget with alerts on the resource group.",
        "",
    ]
    return "\n".join(lines)
